### ISSUE TITLE
Only a single outbound should be provided per-service

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-python#26] opened 2016-02-25 21:27 UTC
In #15,

    RPC(
        ...
        outbounds={
            'yarpc-test': [HTTPOutbound()]
        },
    )

You want to change that to a single outbound per service as per other languages.

**Comment by breerly** [comment] 2016-02-25 21:34
duplicate of #10

**Closed by breerly** 2016-02-25 21:34 UTC
